### ISSUE TITLE
Getting a CookieNotValidError

### ISSUE THREAD

**Issue by ghost** [pietrocaselani/Instagram-Saved-Posts#1]
Hi,
Thanks Pietro for this nice project. Currently, I am getting the following error on running `npm start` from the project directory.
```bash
> instagram-saved-posts@1.0.0 start /home/username/instagram-saver
> node index.js

{ [CookieNotValidError: Cookie `sessionid` you are searching found was either not found or not valid!]
  name: 'CookieNotValidError',
  message:
   'Cookie `sessionid` you are searching found was either not found or not valid!' }
```

Can someone please suggest me how to resolve this, with a light explanation of what's happening?

**Comment by pietrocaselani** [comment]
Looks like related to this issue https://github.com/huttarichard/instagram-private-api/issues/493
Just pull the changes from master branch and it will work.
Let me know if you need any more help

**Comment by ghost** [comment]
Cloned the repo again. It works! Thanks a ton.
