### ISSUE TITLE
405 Method Not Allowed Error

### ISSUE THREAD

**Issue by theritvars** [pietrocaselani/Instagram-Saved-Posts#8]
Started getting this error today:

> Error: IgResponseError: POST /api/v1/feed/saved/ - 405 Method Not Allowed;

Any ideas?

**Comment by theritvars** [comment]
The error has been fixed in `instagram-private-api`, unsure when it will be pushed to npm.

https://github.com/dilame/instagram-private-api/pull/1157/commits/a9fa51db98c68c4173860e63fbc2e2c1c57365f3

Current workaround is to change `node_modules\instagram-private-api\dist\feeds\saved.feed.js` request method from `POST` to `GET` manually.

**Comment by pietrocaselani** [comment]
Hello @RichusX 
Thanks for looking into this!

Let's wait for this to be available on npm then I can update the package.

**Comment by theritvars** [comment]
I believe this has now been fixed in upstream. Newest version of `instagram-private-api` works fine.

**Comment by pietrocaselani** [comment]
Thanks @RichusX 

I pushed two commits on master.

Let me know if there is anything else I can help with.

**Comment by theritvars** [comment]
Looks good. Cheers @pietrocaselani!
