### ISSUE TITLE
How to integrate with a webhook

### ISSUE THREAD

**Issue by drumsetdan13** [pietrocaselani/Instagram-Saved-Posts#9]
Hello! I'm brand new to GitHub but found this file when searching for a way to trigger an automation based on saved posts in Instagram. Can someone kindly explain how to use these files? I have no coding experience? I'd like to connect with zapier and airtable. 

Please reference post: https://community.zapier.com/ask-the-community-3/possible-to-trigger-off-of-instagram-liked-or-saved-post-2268

**Comment by pietrocaselani** [comment]
Hello @drumsetdan13 

My understanding is that you need some way to "listen" when a post was saved on Instagram and then you need to perform some work, like sending to Zapier.

I think this project will not help you in the way you need it. This project only fetches all the saved posts and creates a JSON file containing the link of the post and links for each picture.

There is this project https://github.com/dilame/instagram-private-api that I am using to connect to Instagram, and maybe this can help you.

Still, I don't think Instagram has a way to "listen" for new saved posts, so you would need to do this work manually, by running your integration once a day for example, or some other solution.

My suggestion is to use https://github.com/dilame/instagram-private-api (note this is not an official tool from Instagram) to do the work you specifically need.

**Comment by pietrocaselani** [comment]
I am closing this @drumsetdan13 

Let me know if you need any futher help.
